version: '3.8'

services:
  redis:
    image: redis:7.0.5
    container_name: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    entrypoint:
      - redis-server
      - --save ""
      - --appendonly no
